### ISSUE TITLE
Check .cshtml files don't have build target NONE

### ISSUE THREAD

**Issue by bartvanderwal** [bartvanderwal/checkvsincludes#1]
This can also cause unexpected issues after deploy.

**Comment by bartvanderwal** [comment]
I just found out this actually already works out of the box :smile: 

The package currently checks all/only includes that have a 'Build Action' of 'Content' in Visual Studio.
So .cshtml with a Build Action of 'None' or any other are also reported if you simply add them to the 'stuff to check'

``` javascript
checkVSIncludes('/Views/**/*.cshtml');
```

Or just add it to an existing check:

``` javascript
checkVSIncludes(['/app/**/*.js', '/Content/**/*.less', '/Views/**/*.cshtml']);
```

**Comment by rogerfar** [comment]
Thanks! You mind publishing this to NPM?

**Comment by bartvanderwal** [comment]
?

**Comment by rogerfar** [comment]
Ok wrong issue..

**Comment by bartvanderwal** [comment]
I just updated npm to 0.2.5.

**Comment by rogerfar** [comment]
Perfect, thanks!
