### ISSUE TITLE
Doesn't work for Typescript files

### ISSUE THREAD

**Issue by rogerfar** [bartvanderwal/checkvsincludes#7]
It will say they are not included in the project, probably because they are a special build type of TypeScriptCompile

**Comment by bartvanderwal** [comment]
Ah yes, known issue. Logic has to be extended for this. Only standard 'Build' type files are now seen as present. Any change you can dig into this yourself and do PR?  I'm buried in a customer project currently.

**Comment by bartvanderwal** [comment]
Fixed by @yesman85 in #8.

**Comment by rogerfar** [comment]
I was going to ask here.. Could you publish an update to the NPM package: https://www.npmjs.com/package/check-vs-includes

**Comment by bartvanderwal** [comment]
Ah right, I have to republish to get the latest version in NPM! I'll look into it.
